name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - bison
  - cmake
  - xorg-libxcomposite
  - ffmpeg
  - cython<3
  - pandoc
  - pip
  - pip:
      - -r docs_requirements.txt
