name: NMODL CI

on:
  push:
    branches: 
      - master
      - live-debug*
      - release/**
  pull_request:
    branches:
      - master
      - release/**

env:
  BUILD_TYPE: Release
  DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
  DEFAULT_PY_VERSION: 3.8
  DESIRED_CMAKE_VERSION: 3.8.0

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}

    env:
      INSTALL_DIR: install
      SDK_ROOT: $(xcrun --sdk macosx --show-sdk-path)

    strategy:
      matrix:
        os: [ ubuntu-18.04, macOS-10.15 ]
      fail-fast: true

    steps:

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: ${{ env.DESIRED_CMAKE_VERSION }}
          
      - name: Install homebrew packages
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew install coreutils bison flex boost openmpi
        shell: bash

      - name: Install apt packages
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install flex bison dvipng doxygen libfl-dev pandoc python3-dev python3-pip texlive-latex-recommended texlive-latex-extra
        shell: bash

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        env:
          PYTHON_VERSION:  ${{ env.DEFAULT_PY_VERSION }}
       
      - name: Install Python3 dependencies
        run: |
          pip3 install -U pip setuptools scikit-build Jinja2 PyYAML pytest 'sympy>=1.3'
          
      - uses: actions/checkout@v2
        
      - name: Build and Test
        id: build-test
        shell: bash
        working-directory: ${{runner.workspace}}/nmodl
        run:  |
          if [[ "${{ startsWith(matrix.os, 'macOS') }}" = "true" ]]; then
              export PATH=/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH;
              export CXX=g++;
              export CC=gcc;
          fi
          if [[ "${{ startsWith(matrix.os, 'ubuntu') }}" = "true" ]]; then
              export CXX=c++;
              export CC=cc;
          fi
          echo "------- Build, Test and Install -------"
          mkdir build && pushd build
          cmake .. -DPYTHON_EXECUTABLE=$(which python3) -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
          make;
          if [ $? -ne 0 ]; then
            make VERBOSE=1;
          fi
          ctest -VV
          make install
         
        env:
          INSTALL_DIR: ${{ runner.workspace }}/install

      # This step will set up an SSH connection on tmate.io for live debugging.
      # To trigger it, simply prefix your branch name with `live-debug`
      #   i.e.: live-debug-hocfix
      - name: live debug session on failure
        if: failure() && startsWith(github.ref, 'refs/heads/live-debug')
        uses: mxschmitt/action-tmate@v3

      - name: Documentation 
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        id: documentation
        working-directory: ${{runner.workspace}}/nmodl
        run: |
          echo "------- Build Documentation -------";
          python3 setup.py build_ext --inplace docs -j 2 -G "Unix Makefiles";
          cd _skbuild/linux-x86_64-3.8/setuptools/sphinx;
          rm -rf doctest doctrees && touch .nojekyll;
          echo "<meta http-equiv=\"refresh\" content=\"0; url=./html/index.html\" />" > index.html;
          echo ::set-output name=status::done
          
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: steps.documentation.outputs.status == 'done' && startsWith(github.ref, 'refs/heads/master')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ${{runner.workspace}}/nmodl/_skbuild/linux-x86_64-3.8/setuptools/sphinx # The folder the action should deploy.
          CLEAN: false # Automatically remove deleted files from the deploy branch
  
  coverage:
    runs-on: ubuntu-18.04
    name: "Coverage Test"
    steps:
      - name: Install packages
        run: |
          sudo apt-get install doxygen bison flex libfl-dev libboost-all-dev libopenmpi-dev openmpi-bin python3-dev python3-pip lcov
        shell: bash
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        env:
          PYTHON_VERSION:  ${{ env.DEFAULT_PY_VERSION }}
      - name: Install Python3 dependencies
        run: |
          pip3 install -U pip setuptools scikit-build Jinja2 PyYAML pytest 'sympy>=1.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Build and Test for Coverage
        id: codecov
        shell: bash
        working-directory: ${{runner.workspace}}/nmodl
        run:  |
          mkdir build && cd build
          cmake .. -DPYTHON_EXECUTABLE=$(which python3) -DCMAKE_C_FLAGS="-coverage -O0" -DCMAKE_CXX_FLAGS="-coverage -O0";
          make
          (cd ..;  lcov --capture  --initial --directory . --no-external --output-file build/coverage-base.info)
          make test
          (cd ..; lcov --capture  --directory . --no-external --output-file build/coverage-run.info)
          lcov --add-tracefile coverage-base.info --add-tracefile coverage-run.info --output-file coverage-combined.info
          genhtml coverage-combined.info --output-directory coverage --demangle-cpp --ignore-errors source
          bash <(curl -s https://codecov.io/bash)
