name: Template for publishing release or nightly NEURON Python wheels

on:
  workflow_call:
    inputs:
      project_name:
        description: The name of the PyPI project
        options:
          - 'neuron-nightly'
          - 'neuron'

jobs:
  pypi-publish:
    name: Upload wheels to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ inputs.project_name }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download wheels from artifact
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: wheelhouse/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
