name: Build NEURON Python wheels for CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build and test NEURON Python wheels
    uses: ./.github/workflows/wheels_template.yml
    with:
      platform: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}
      commit: ${{ github.sha }}
    strategy:
      matrix:
        os: ['macos-14', 'ubuntu-22.04-arm']
        python_version: ['3.9', '3.13']

  merge:
    name: Merge artifacts and post artifacts URL
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: Merge Artifacts
        id: merge-artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
          name: wheels
          pattern: wheels-*

      - name: Create comment with URL to artifact
        if: github.event.pull_request
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✔️ ${{ github.event.pull_request.head.sha }} -> [artifacts URL](${{ steps.merge-artifacts.outputs.artifact-url }})
